name: rocky-test

on:
  workflow_dispatch:
     inputs:
        release:
          description: '版本'
          required: true
          default: '9'

jobs:
  build:
    name: rocky-${{ matrix.release }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: handle release
        run: |
          sed -i 's|rockylinux/rockylinux:9|rockylinux/rockylinux:${{ github.event.inputs.release }}|' ./rocky/DockerfileTest

      - name: Build And Push
        uses: docker/build-push-action@v
        with:
          context: .
          file: ./rocky/DockerfileTest
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/codetiger666/images/rocky:${{ github.event.inputs.release }}
